const { chromium } = await import(new URL('../.build/browser/node_modules/playwright/index.mjs',import.meta.url));
const url=process.env.MONITOR_URL||'http://127.0.0.1:8765/';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const response=await page.request.get(new URL('/api/status',url).href);const initial=await response.json();
assert.equal((await page.request.post(new URL('/api/status',url).href)).status(),405);
assert.equal((await page.request.get(new URL('/policy.bcmc',url).href)).status(),404);
await page.goto(url,{waitUntil:'networkidle'});
await page.waitForFunction(()=>document.getElementById('state').textContent==='RUNNING');
assert.equal(await page.locator('#population .row').count(),18);
assert.equal(await page.locator('#population .stage-detail').count(),18);
assert.equal(Number((await page.locator('#agents').textContent()).replaceAll(',','')),initial.active_agents);
assert.equal(await page.locator('#error').textContent(),'');
assert.ok((await page.locator('#speedchart .line').getAttribute('d')).length>0);
await page.screenshot({path:'.build/monitor-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'.build/monitor-mobile.png',fullPage:true});
await page.route('**/api/status',async route=>{
 const response=await route.fetch();const data=await response.json();data.epoch_millis=Date.now()-60000;
 await route.fulfill({response,json:data});
});
await page.reload({waitUntil:'networkidle'});
await page.waitForFunction(()=>document.getElementById('state').textContent==='STALE');
assert.equal(await page.locator('#rate').textContent(),'—');
assert.ok((await page.locator('#error').textContent()).includes('historical'));
assert.deepEqual(errors,[]);
console.log('PASS live dashboard, 18-stage display, desktop/mobile bounds, charts, stale-state warning; no browser errors');
await browser.close();
